const lessonData = {

  2: {
    checkpoint: false,
    last: false,
    checkpoints: [],
    images: [
      {
        alt: "Mt Sinai security officer",
        image:
          "https://chaplaincy-innovation-lab-lessons.s3.us-east-1.amazonaws.com/2025-01/unnamed.png",
        order: 0,
      },
    ],
    layoutNumber: 4,
    navigation: [
      { available_scene: "4", current_scene: "2", previous_scene: "1",text: "Continue" },
    ],
    scene_number: "2",
    sidebar: false,
    sidebarImages: [],
    sidebarVideos: [],
    sidebarText: [],
    text: [
      `<p>The COVID-19 pandemic impacted everyone, especially those who work in healthcare organizations. A study published in 2021 found that 40% of healthcare workers were experiencing depression, anxiety, a stress disorder or moral injury. The Mount Sinai Health System opened the <a href="https://icahn.mssm.edu/research/center-stress-resilience-personal-growth" target="_blank" rel="noopener noreferrer">Center for Stress Resilience and Personal Growth</a> (CSRPG) in June 2020 as a, “resource available to all Mount Sinai faculty, staff, trainees, and medical and graduate students. Our Center has a long name but a simple mission – provide scientifically-grounded services that support the resilience and psychological well-being of our Mount Sinai community.” </p>

<p>The CSRPG is staffed by social workers, psychologists, psychiatrists and a healthcare chaplain and offers resilience workshops, individualized support, wellness hubs, and a range of other programs. Since its inception in 2020, CSRPG has conducted over 17,000 visits with 1,381 unique patients. In addition, CSRPG has conducted 840 Resilience workshops and huddles with over 2000 individuals. </p>`
    ],
    title: null,
    videos: [],
    audio: [],
  },
  
  4: {
    checkpoint: false,
    last: false,
    checkpoints: [], 
    images: [
    ],
    layoutNumber: 1,
    navigation: [
      { available_scene: "5", current_scene: "4", previous_scene: "2",text: "Continue" },
    ],
    scene_number: "4",
    sidebar: false,
    sidebarImages: [],
    sidebarVideos: [],
    sidebarText: [],
    text: [
      `<p>Security officers are a frequently overlooked group of front-line workers in healthcare organizations where they are staffed 24 hours a day, 7 days a week. Their long work hours combined with physical hazards, sometimes challenging interactions with the public, and germs/pathogens can lead to exhaustion, distress and burnout.</p>

<p>During the pandemic, they were responsible for keeping healthcare organizations safe and secure while managing their own exposure to COVID-19. In the Mount Sinai Health System, security officers filled many roles during the pandemic, including new roles generated by the epidemic. CSRPG aims to serve all members of the Mount Sinai Health System, including security officers.
</p>`,
    ],
    title: "An Overlooked Group",
    videos: [],
    audio: [],
  },
  5: {
    checkpoint: false,
    last: false,
    checkpoints: [],
    images: [
      {
        alt: "Press conference",
        image:
          "https://chaplaincy-innovation-lab-lessons.s3.us-east-1.amazonaws.com/2025-01/shutterstock_376505077.jpg",
        order: 0,
      },
    ],
    layoutNumber: 4,
    navigation: [
      { available_scene: "6", current_scene: "5", previous_scene: "4",text: "Continue" },
    ],
    scene_number: "5",
    sidebar: false,
    sidebarImages: [],
    sidebarVideos: [],
    sidebarText: [],
    text: [
      `<p>A few short hours later, Dr. Hendel stood next to the Mayor and Police Chief at a short televised press conference. "It is with a heavy heart that I address you today.” she said somberly. "I'm heartbroken to announce that two members of our employee family have been killed, and another is in critical condition.”</p><p>She took a shallow breath and continued explaining that throughout the entire event, "our first priority was to ensure the safety of our patients - and that they were well cared for.” She continued, "I can assure you that our patients are safe.”</p>

<p>As details emerged, the hospital and public learned that, "A pharmacy technician showed up for work at Long Beach Memorial Medical Center…brandishing two handguns, killed his boss and another manager and then fatally shot himself.” <strong>This was not a random act as the perpetrator Mario Ramirez sought out and killed Hugo Bustamante and Kelly Hales before turning the gun on himself.</strong></p>`,
    ],
    title: null,
    videos: [],
    audio: [],
  },
  6: {
    checkpoint: false,
    last: false,
    checkpoints: [],
    images: [],
    layoutNumber: 4,
    navigation: [
      { available_scene: "7", current_scene: "6", previous_scene: "5",text: "Continue" },
    ],
    scene_number: "6",
    sidebar: false,
    sidebarImages: [],
    sidebarVideos: [],
    sidebarText: [],
    text: [
      `<p>In the difficult days that followed Dr. Hendel and leaders across the hospital and the healthcare system worked with colleagues in public safety, crisis response, regulatory issues, human resources, and spiritual care to work with the living and the dead.</p><p>In addition to helping the families of those who died navigate post-employment procedures, the chaplains were asked to help plan and conduct onsite memorial services for those who were killed, all three of whom were members of the hospital community. </p>`,
    ],
    title: "The Spiritual Care Team's Responsibilities",
    videos: [],
    audio: [],
  },    
  7: {
    checkpoint: false,
    last: false,
    checkpoints: [],
    images: [],
    layoutNumber: 4,
    navigation: [
      { available_scene: "8", current_scene: "7", previous_scene: "6",text: "Continue" },
    ],
    scene_number: "7",
    sidebar: false,
    sidebarImages: [],
    sidebarVideos: [],
    sidebarText: [],
    text: [
      `<p>In Dr. Hendel's words, "Because we were fortunate to have a large and diverse team of pastors on staff who were experienced in conducting memorial and remembrance services in addition to their usual duties as hospital chaplains, it wasn't uncommon for us to hold services on site when an employee, physician or volunteer passed away. We'd also become accustomed to holding them for board members, community members, and long-time patients whom we'd grown close to and considered part of our organizational family. Sometimes the services were held in addition to a funeral hosted by their family and sometimes they were held in lieu of one. It has become a hallmark of our culture, reflecting our mission for caring for the people in our community at all stages of life, from beginning to end.”</p>

<p>"There was no question that we'd be hosting memorial services for our colleagues - we knew it would be necessary to honor them and collectively grieve as an organization. And even though we had a large auditorium that could accommodate several hundred people, we knew it would be overflowing at each service” (p. 89-90). In addition to colleagues in the hospital, Kelly and Hugo were active in professional associations of pharmacists and the alumni networks of alma maters. 
</p>`,
    ],
    title: "The Spiritual Care Team's Responsibilities",
    videos: [],
    audio: [],
  },    
  8: {
    checkpoint: false,
    last: false,
    checkpoints: [{
      alt: null,
      answer: false,
      content_type: 5,
      data:
        `<ul><li>What went well in this situation? How did the chaplain work with stakeholders to memorialize a complex situation?</li>
        <li>How might race, class, and gender have impacted how decisions were made in this situation?</li>
        <li>How should organizations make decisions about memory in situations like this? For instance, putting the victims’ names on the monument, holding memorial services? Who should be involved in making these decisions? </li>
        </ul>`,
      order: 0,
      question_type: 2,
      scene_number: "8",
      sidebar: false,
    }],
    images: [],
    layoutNumber: 9,
    navigation: [
      { available_scene: "10", current_scene: "7", previous_scene: "6",text: "Continue" },
    ],
    scene_number: "7",
    sidebar: false,
    sidebarImages: [],
    sidebarVideos: [],
    sidebarText: [],
    text: [],
    title: null,
    videos: [],
    audio: [],
  },
  
  10: {
    checkpoint: false,
    last: true,
    checkpoints: [],
    images: [],
    layoutNumber: 6,
    navigation: [{available_scene: "10", current_scene: "10", previous_scene: "7",text: "End Lesson" }],
    scene_number: "10",
    sidebar: false,
    sidebarImages: [],
    sidebarVideos: [],
    sidebarText: [],
    text: [
      `<p>You finished this lesson! You made important decisions about how to deal with violence, trauma, and grief in the workplace. You learned how to balance stakeholder opinions with the needs of those who were most directly affected by violence. These were not easy decisions, and in some instances, there weren't any clear cut answers. </p>`
    ],
    title: "Lesson complete",
    videos: [],
    audio: [],
  },
};

export default lessonData;